spring:
  application:
    name: jasperreports
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
